name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Configure '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happens
      placeholder: What actually happens?
    validations:
      required: true

  - type: input
    id: typo3-version
    attributes:
      label: TYPO3 Version
      description: Which TYPO3 version are you using?
      placeholder: e.g., 13.4.3
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP version are you using?
      placeholder: e.g., 8.3.10
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Which version of dp_t3_toc are you using?
      placeholder: e.g., 3.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this issue occur?
      multiple: true
      options:
        - Local Development
        - Staging/Testing
        - Production
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant TypoScript configuration or DataProcessor settings
      placeholder: |
        10 = Ndrstmr\DpT3Toc\DataProcessing\TocProcessor
        10 {
            pidInList = this
            mode = sectionIndexOnly
        }
      render: typoscript

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error logs
      placeholder: Error logs from typo3temp/var/log/
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Other extensions installed that might conflict?
        - Special server configuration?
        - Database type/version?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched for similar issues
          required: true
        - label: I can reproduce this issue consistently
          required: true
        - label: I have provided all required information
          required: true
